<a href="https://colab.research.google.com/github/nameerkhan1/Medical-health-care-analysis/blob/main/Hospital_data_analysis_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [ ]:
# Load the CSV file
file_path = '/content/drive/MyDrive/Colab Notebooks/hospital_data_unclean.csv'
df = pd.read_csv(file_path)

In [ ]:
#View the first 5 rows
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,M,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02/02/2024,Paracetamol,N
1,LEsliE tErrY,62.0,M,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,dAnnY SMiTH,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,ADRIeNNe bELL,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10/09/2022,Penicillin,abn

In [ ]:
df.isna()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False
3,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
55501,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
55502,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
55503,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False
55504,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False

In [ ]:
df.shape

(55505, 15)

In [ ]:
df ['Name']=df['Name'].str.title()
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,M,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02/02/2024,Paracetamol,N
1,Leslie Terry,62.0,M,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10/09/2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,M,B+,HYPERTENSION,02/21/2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,M,A+,HYPERTENSION,23-10-2019,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,M,O--,OBESITY,20-12-2019,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020.01.05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024.03.21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04/19/2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07/18/2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,NaN,Penicillin,N

In [ ]:
df['Gender']=df['Gender'].replace(['M','F'],['Male','Female'])
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,Male,B-,CANCER,2024.01.31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02/02/2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019.08.20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09/22/2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11/18/2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020.12.18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022.09.19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10/09/2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02/21/2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-2019,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020.01.05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024.03.21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04/19/2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07/18/2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,NaN,Penicillin,N

In [ ]:
df['Date of Admission']=df['Date of Admission'].astype(str)
df["Discharge Date"]=df['Discharge Date'].astype(str)

In [ ]:
df['Date of Admission']=df['Date of Admission'].str.replace(".","-",regex=False)
df['Date of Admission']=df['Date of Admission'].str.replace("/","-",regex=False)
df["Discharge Date"]=df['Discharge Date'].str.replace(".","-",regex=False)
df["Discharge Date"]=df['Discharge Date'].str.replace("/","-",regex=False)

In [ ]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith ##,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies ##,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells ##,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna ##,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya ##,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez ##,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-2019,Daryl Mckinney ##,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe ##,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins ##,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Doctor'] = df['Doctor'].str.replace("#",'')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,"Sons and Miller,,",Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,"Kim Inc,,",Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,"Cook PLC,,",Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,"Hernandez Rogers and Vang,,,",Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,"Walls-Castillo,,",NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,"and Byrd Carroll, Washington,,",Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-2019,Daryl Mckinney,"Austin, Morgan and Ellis,,",NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,"Hobbs-Sullivan,,",Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Hospital'] = df['Hospital'].str.replace(",",'')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+-,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O--,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-+,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Insurance Provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'UnitedHealthcare',
       'Cigna'], dtype=object)

In [ ]:
import re

def standardize_blood_type(bt):
    if pd.isna(bt):
        return bt
    bt = str(bt).strip().upper()
    # Remove any character that is not A, B, O, +, -
    bt = re.sub(r'[^ABO+\-]+', '', bt)

    if not bt: # Handle empty strings after cleaning
        return None

    # Handle common incorrect representations
    replacements = {
        'B-+': 'B+', 'AB+-': 'AB+', 'A+-': 'A+', 'AB-+': 'AB+', 'B+-': 'B+',
        'B++': 'B+', 'A--': 'A-', 'AB++': 'AB+', 'O++': 'O+', 'A-+': 'A+',
        'B--': 'B-', 'AB--': 'AB-', 'O--': 'O-', 'O+-': 'O+', 'O-+': 'O-',
        'A +': 'A+', 'A -': 'A-', 'B +': 'B+', 'B -': 'B-',
        'AB +': 'AB+', 'AB -': 'AB-', 'O +': 'O+', 'O -': 'O-',
    }
    for old, new in replacements.items():
        bt = bt.replace(old, new)

    # Further simplification: if multiple + or -
    bt = re.sub(r'\++', '+', bt)
    bt = re.sub(r'-+', '-', bt)

    # Final check for valid blood types (A, B, AB, O with +/-)
    if bt in ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']:
        return bt
    else:
        # For anything still not standard, set to 'UNKNOWN_BLOOD_TYPE'
        return 'UNKNOWN_BLOOD_TYPE'

df['Blood Type'] = df['Blood Type'].apply(standardize_blood_type)

df['Insurance Provider'] = df['Insurance Provider'].str.replace("H"," H")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,NaN,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,NaN,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Blood Type'].value_counts()

Blood Type
AB+    8003
B+     8000
A+     7972
O+     6348
O-     6306
A-     4859
B-     4818
AB-    4759
Name: count, dtype: int64

In [ ]:
df['Insurance Provider'].unique()

array(['Blue Cross', 'Medicare', 'Aetna', nan, 'United Healthcare',
       'Cigna'], dtype=object)

In [ ]:
df.isna().sum()

Name                  4440
Age                   4440
Gender                4440
Blood Type            4440
Medical Condition     4440
Date of Admission        0
Doctor                4440
Hospital              4441
Insurance Provider    4442
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [ ]:
df['Name']=df['Name'].fillna("unknown")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Age'].fillna(df['Age'].mean(),inplace=True)
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Gender'].value_counts()

Gender
Male      25605
FEMALE    25460
Name: count, dtype: int64

In [ ]:
df['Gender'].value_counts().index[0]

'Male'

In [ ]:
df['Gender'].fillna(df['Gender'].mode()[0],inplace=True)
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Gender'].value_counts()

Gender
Male      30045
FEMALE    25460
Name: count, dtype: int64

In [ ]:
df['Blood Type']=df['Blood Type'].fillna(df['Blood Type'].mode()[0])
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,NaN,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Blood Type'].value_counts()

Blood Type
AB+    12443
B+      8000
A+      7972
O+      6348
O-      6306
A-      4859
B-      4818
AB-     4759
Name: count, dtype: int64

In [ ]:
df['Doctor']=df['Doctor'].fillna('Unknown')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Doctor'].value_counts()

Doctor
Unknown              4440
Michael Smith          24
John Smith             21
Michael Johnson        20
Robert Smith           19
                     ...
Brady Burke             1
Laura Robinson          1
Kristen King            1
Nicholas Schmidt        1
Bernard Ruiz            1
Name: count, Length: 37820, dtype: int64

In [ ]:
df['Medical Condition'].value_counts()

Medical Condition
ARTHRITIS       8598
DIABETES        8574
HYPERTENSION    8507
OBESITY         8497
ASTHMA          8459
CANCER          8430
Name: count, dtype: int64

In [ ]:
df['Medical Condition']=df['Medical Condition'].fillna('Unknown')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,NaN,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,NaN,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Medical Condition'].value_counts()

Medical Condition
ARTHRITIS       8598
DIABETES        8574
HYPERTENSION    8507
OBESITY         8497
ASTHMA          8459
CANCER          8430
Unknown         4440
Name: count, dtype: int64

In [ ]:
df['Hospital'].value_counts()

Hospital
LLC Smith                           38
Smith Ltd                           36
Ltd Smith                           36
Smith Group                         34
Johnson Inc                         33
                                    ..
Morris-Brady                         1
and Hayes Williams Walker            1
Rodriguez and Fernandez Alvarado     1
Rodriguez-Rose                       1
Grimes and Turner Turner             1
Name: count, Length: 37356, dtype: int64

In [ ]:
df['Hospital']=df['Hospital'].fillna('Unknown')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,NaN,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,NaN,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,NaN,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Hospital'].value_counts()

Hospital
Unknown                       4441
LLC Smith                       38
Smith Ltd                       36
Ltd Smith                       36
Smith Group                     34
                              ...
and Moreno Crosby Young          1
Khan-Snow                        1
and Wilson Hampton Roberts       1
and Gray Fleming Young           1
Anderson-Wright                  1
Name: count, Length: 37357, dtype: int64

In [ ]:
df['Insurance Provider'].value_counts()

Insurance Provider
Cigna                10361
United Healthcare    10247
Medicare             10241
Blue Cross           10192
Aetna                10022
Name: count, dtype: int64

In [ ]:
df['Insurance Provider']=df['Insurance Provider'].fillna('Unknown')
df['Billing Amount']=df['Billing Amount'].astype(str)
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155 USD,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885 USD,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456 USD,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528 USD,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317813937623 USD,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381722682367 USD,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389 USD,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.9788574008 USD,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.88736491442 USD,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194 USD,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Billing Amount']=df['Billing Amount'].astype(str)

In [ ]:
df['Billing Amount']=df['Billing Amount'].str.replace("USD","")
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281305978155,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327286577885,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096078842456,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78240987528,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317813937623,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381722682367,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616670892389,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.9788574008,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.88736491442,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.14810411194,NaN,Emergency,nan,Penicillin,N

In [ ]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [ ]:
df['Billing Amount']=df['Billing Amount'].astype(float)

In [ ]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount        4440
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication            4440
Test Results          4440
dtype: int64

In [ ]:
df['Billing Amount'] = pd.to_numeric(df['Billing Amount'].astype(str).str.strip(), errors='coerce')
df['Billing Amount'].fillna(df['Billing Amount'].mean(), inplace=True)
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Medication'].value_counts()

Medication
Lipitor        10281
Ibuprofen      10245
Aspirin        10205
Paracetamol    10167
Penicillin     10167
Name: count, dtype: int64

In [ ]:
df['Medication']=df['Medication'].fillna('Unknown')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Medication'].value_counts()

Medication
Lipitor        10281
Ibuprofen      10245
Aspirin        10205
Paracetamol    10167
Penicillin     10167
Unknown         4440
Name: count, dtype: int64

In [ ]:
df['Test Results'].value_counts()

Test Results
abn        17123
N          17039
unknown    16903
Name: count, dtype: int64

In [ ]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number           4441
Admission Type        4440
Discharge Date           0
Medication               0
Test Results          4440
dtype: int64

In [ ]:
df['Test Results']=df['Test Results'].fillna('Unknown')
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-2024,Paracetamol,N
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-2019,Ibuprofen,unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,09-22-2022,Unknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-2022,Aspirin,N
3,unknown,28.0,FEMALE,O+,DIABETES,11-18-2020,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,abn
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-2022,Penicillin,abn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,02-21-2022,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-2022,Ibuprofen,unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,23-10-2019,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-2019,Paracetamol,unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,20-12-2019,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,abn
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,07-18-2019,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,NaN,Emergency,nan,Penicillin,N

In [ ]:
df['Test Results'].value_counts()

Test Results
abn        17123
N          17039
unknown    16903
Unknown     4440
Name: count, dtype: int64

In [ ]:
df['Test Results']=df['Test Results'].str.replace("u","U")

In [ ]:
df['Test Results'].value_counts()

Test Results
Unknown    21343
abn        17123
N          17039
Name: count, dtype: int64

In [ ]:
df['Test Results']=df['Test Results'].str.replace("abn","Abnormal")
df['Test Results']=df['Test Results'].str.replace("N","Normal")

In [ ]:
df['Test Results'].value_counts()

Test Results
Unknown     21343
Abnormal    17123
Normal      17039
Name: count, dtype: int64

In [ ]:
df['Room Number']=df['Room Number'].fillna('Not Assigned')

In [ ]:
df.isna().sum()

Name                     0
Age                      0
Gender                   0
Blood Type               0
Medical Condition        0
Date of Admission        0
Doctor                   0
Hospital                 0
Insurance Provider       0
Billing Amount           0
Room Number              0
Admission Type        4440
Discharge Date           0
Medication               0
Test Results             0
dtype: int64

In [ ]:
df['Admission Type']=df['Admission Type'].fillna('unknown')

In [ ]:
df.isna().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [ ]:
df['Date of Admission'] = df['Date of Admission'].astype(str).str.strip()

In [ ]:
df['Discharge Date'] = df['Discharge Date'].astype(str).str.strip()

In [ ]:
dates = pd.to_datetime(df['Date of Admission'],errors='coerce')

In [ ]:
mask = dates.isna()

In [ ]:
mask

0        False
1        False
2         True
3         True
4        False
         ...
55500     True
55501     True
55502     True
55503    False
55504     True
Name: Date of Admission, Length: 55505, dtype: bool

In [ ]:
dates[mask] = pd.to_datetime(df.loc[mask,"Date of Admission"],errors="coerce",dayfirst=True)

In [ ]:
df['Date of Admission'] = dates

In [ ]:
df['Date of Admission'].fillna(df['Date of Admission'].median(),inplace=True)

In [ ]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-2024,Paracetamol,Normal
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-2019,Ibuprofen,Unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,2022-09-22,Unknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-2022,Aspirin,Normal
3,unknown,28.0,FEMALE,O+,DIABETES,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,2022-02-21,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-2022,Ibuprofen,Unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,2021-11-01,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-2019,Paracetamol,Unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,2021-11-01,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,Abnormal
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,Unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,2019-07-18,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,Not Assigned,Emergency,nan,Penicillin,Normal

In [ ]:
df['Blood Type'] = df['Blood Type'].astype(str).str.upper()

In [ ]:
df['Blood Type'] =df['Blood Type'].str.replace(r"(\+|-)+$",lambda x: x.group(0)[0].upper(),regex=True)

In [ ]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328.0,Urgent,02-02-2024,Paracetamol,Normal
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265.0,Emergency,26-08-2019,Ibuprofen,Unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,2022-09-22,Unknown,Cook PLC,Aetna,27955.096079,205.0,Emergency,07-10-2022,Aspirin,Normal
3,unknown,28.0,FEMALE,O+,DIABETES,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.782410,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.317814,458.0,Urgent,10-09-2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,2022-02-21,Cassandra Montoya,Walls-Castillo,Unknown,19601.381723,420.0,Emergency,09-03-2022,Ibuprofen,Unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,2021-11-01,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.616671,357.0,Urgent,20-11-2019,Paracetamol,Unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,2021-11-01,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.978857,136.0,Elective,2020-01-05,Aspirin,Abnormal
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.887365,448.0,Elective,04-19-2024,Ibuprofen,Unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,2019-07-18,Roy Perkins,Hobbs-Sullivan,Medicare,42709.148104,Not Assigned,Emergency,nan,Penicillin,Normal

In [ ]:
df['Blood Type'].value_counts()

Blood Type
AB+    12443
B+      8000
A+      7972
O+      6348
O-      6306
A-      4859
B-      4818
AB-     4759
Name: count, dtype: int64

In [ ]:
df['Billing Amount']=df['Billing Amount'].round(2)

In [ ]:
df

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,unknown,30.0,Male,B-,CANCER,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.28,328.0,Urgent,02-02-2024,Paracetamol,Normal
1,Leslie Terry,62.0,Male,A+,OBESITY,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.33,265.0,Emergency,26-08-2019,Ibuprofen,Unknown
2,Danny Smith,76.0,FEMALE,A-,OBESITY,2022-09-22,Unknown,Cook PLC,Aetna,27955.10,205.0,Emergency,07-10-2022,Aspirin,Normal
3,unknown,28.0,FEMALE,O+,DIABETES,2020-11-18,Kevin Wells,Hernandez Rogers and Vang,Medicare,37909.78,450.0,Elective,2020-12-18,Ibuprofen,Abnormal
4,Adrienne Bell,43.0,FEMALE,AB+,CANCER,2022-09-19,Kathleen Hanna,Unknown,Unknown,14238.32,458.0,Urgent,10-09-2022,Penicillin,Abnormal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55500,Cassandra Carney,32.0,Male,B+,HYPERTENSION,2022-02-21,Cassandra Montoya,Walls-Castillo,Unknown,19601.38,420.0,Emergency,09-03-2022,Ibuprofen,Unknown
55501,Dr. David Smith,18.0,Male,A+,HYPERTENSION,2021-11-01,Eric Martinez,and Byrd Carroll Washington,Blue Cross,6459.62,357.0,Urgent,20-11-2019,Paracetamol,Unknown
55502,Lisa Allen,65.0,Male,O-,OBESITY,2021-11-01,Daryl Mckinney,Austin Morgan and Ellis,Unknown,36639.98,136.0,Elective,2020-01-05,Aspirin,Abnormal
55503,Aaron Craig,22.0,FEMALE,O-,ARTHRITIS,2024-03-21,Justin Wolfe,Unknown,Medicare,13007.89,448.0,Elective,04-19-2024,Ibuprofen,Unknown
55504,Ashley Macdonald,36.0,FEMALE,B+,HYPERTENSION,2019-07-18,Roy Perkins,Hobbs-Sullivan,Medicare,42709.15,Not Assigned,Emergency,nan,Penicillin,Normal

In [ ]:
df.to_excel("Hospital data cleaned.xlsx",index=False)

In [ ]:
from google.colab import files
files.download("Hospital data cleaned.xlsx")